Spring:
  application:
    name: dev
springdoc:
  api-docs:
    path: /apidocs
  swagger-ui:
    path: /swaggerui.html
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
